# Numpy

In [64]:
import numpy as np
import  sys

In [17]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[0])
print(a[1:3])
print(a[1:-1])
print(a[1::3])
print(a[::-2])

1
[2 3]
[2 3 4 5 6 7 8]
[2 5 8]
[9 7 5 3 1]


In [18]:
a.sum()

45

In [19]:
a.mean()

5.0

In [20]:
a.std()

2.581988897471611

In [21]:
a.var()

6.666666666666667

In [23]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [25]:
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
B.sum()

45

In [27]:
B.sum(axis=1)

array([ 6, 15, 24])

In [28]:
B.sum(axis=0)

array([12, 15, 18])

Numpy Broadcasting and vectorized operations


In [29]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [32]:
a+=20
a

array([20, 21, 22, 23, 24])

In [38]:
a
a[[0,-1]]
a[[True, False, False, False, True]] #boolean and multidimensions will give same ouput

array([20, 24])

In [39]:
a>=2

array([ True,  True,  True,  True,  True])

In [41]:
a[a>=23]

array([23, 24])

In [42]:
a

array([20, 21, 22, 23, 24])

In [43]:
a[~(a> a.mean())]

array([20, 21, 22])

In [45]:
a[(a==20) | (a==24)]

array([20, 24])

In [47]:
randA= np.random.randint(100, size=(3,3))

In [48]:
randA

array([[62, 65, 73],
       [79, 67, 31],
       [37, 91, 88]])

In [51]:
randA >90

array([[False, False, False],
       [False, False, False],
       [False,  True, False]])

Linear Algebra


In [52]:
randA

array([[62, 65, 73],
       [79, 67, 31],
       [37, 91, 88]])

In [56]:
randB= np.random.randint(100,size=(3,3))

In [57]:
randA.dot(randB)

array([[ 3188,  9435, 11270],
       [ 2537,  6021, 11694],
       [ 3731, 10053, 10557]])

In [59]:
randA + randB

array([[ 71, 101, 169],
       [ 97,  70,  78],
       [ 57, 187, 119]])

In [60]:
randA @ randB

array([[ 3188,  9435, 11270],
       [ 2537,  6021, 11694],
       [ 3731, 10053, 10557]])

In [62]:
print(randA)
randA.T


[[62 65 73]
 [79 67 31]
 [37 91 88]]


array([[62, 79, 37],
       [65, 67, 91],
       [73, 31, 88]])

Size of Objects in Memory


In [65]:
sys.getsizeof(1)

28

In [68]:
#Longs are even larger
sys.getsizeof(10**100)

72

In [70]:
np.dtype(np.int8).itemsize

1

In [73]:
np.dtype(np.float64).itemsize

8

In [74]:
l=list(range(1000))

In [75]:
n= np.arange(1000)

In [77]:
%time np.sum(n ** 2)

CPU times: user 123 µs, sys: 16 µs, total: 139 µs
Wall time: 103 µs


332833500

In [78]:
%time sum([x **2 for x in l])

CPU times: user 416 µs, sys: 52 µs, total: 468 µs
Wall time: 475 µs


332833500