# Numpy

In [1]:
import numpy as np

In [17]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[0])
print(a[1:3])
print(a[1:-1])
print(a[1::3])
print(a[::-2])

1
[2 3]
[2 3 4 5 6 7 8]
[2 5 8]
[9 7 5 3 1]


In [18]:
a.sum()

45

In [19]:
a.mean()

5.0

In [20]:
a.std()

2.581988897471611

In [21]:
a.var()

6.666666666666667

In [23]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [25]:
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
B.sum()

45

In [27]:
B.sum(axis=1)

array([ 6, 15, 24])

In [28]:
B.sum(axis=0)

array([12, 15, 18])

Numpy Broadcasting and vectorized operations


In [29]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [32]:
a+=20
a

array([20, 21, 22, 23, 24])